name: build
on:
  - push
env:
  NODE_OPTIONS: --max-old-space-size=4096
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
      - name: Install client dependencies
        run: npm --prefix client ci
      - name: Install server dependencies
        run: npm --prefix server ci
      - name: 'Lint: client'
        run: npm --prefix client run lint
      - name: 'Lint: server'
        run: npm --prefix server run lint
